"""
Graph ↔ text conversion for the LLM fine-tuning pipeline.

Edge-type encoding (gunfolds convention)
-----------------------------------------
  1  →  directed edge  (src → tgt)
  2  →  bidirected edge (src ↔ tgt, stored once: lower src)
  3  →  both directed and bidirected (src → tgt AND src ↔ tgt)

Text format used in prompts/completions
-----------------------------------------
  Directed  :  "1->2"
  Bidirected:  "1<->2"  (only emitted for the lower-numbered node)
  Both      :  "1->2" and "1<->2"
"""

from typing import Optional


EDGE_TYPE_DIRECTED = 1
EDGE_TYPE_BIDIRECTED = 2
EDGE_TYPE_BOTH = 3

SYSTEM_PROMPT = (
    "You are an expert in causal discovery and dynamic Bayesian networks. "
    "Given an observed undersampled causal graph and a list of candidate "
    "causal-timescale graphs generated by RASL, select the candidate that "
    "is most likely to be the true causal-timescale graph. "
    "Output the candidate index (0-based) followed by its edge list."
)


class GraphFormatter:
    """Convert gunfolds graph dicts to/from human-readable text."""

    # ------------------------------------------------------------------
    # Graph → text
    # ------------------------------------------------------------------

    def graph_to_text(self, graph: dict) -> str:
        """Return a compact edge-list string for one graph."""
        directed, bidirected = self._split_edges(graph)
        parts = []
        for src, tgt in sorted(directed):
            parts.append(f"{src}->{tgt}")
        for src, tgt in sorted(bidirected):
            parts.append(f"{src}<->{tgt}")
        return ", ".join(parts) if parts else "(no edges)"

    def to_prompt(
        self,
        g_u: dict,
        candidates: list[dict],
        u: int,
        include_system: bool = True,
    ) -> str:
        """Build the full LLM prompt for one training example.

        Parameters
        ----------
        g_u        : observed undersampled graph (gunfolds dict)
        candidates : list of candidate graphs from RASL
        u          : undersampling rate used to produce g_u
        """
        lines = []
        if include_system:
            lines.append(f"[SYSTEM]\n{SYSTEM_PROMPT}\n")

        lines.append("[OBSERVED UNDERSAMPLED GRAPH]")
        lines.append(f"Undersampling rate: {u}")
        lines.append(f"Edges: {self.graph_to_text(g_u)}")
        lines.append("")

        lines.append(f"[RASL CANDIDATES]  ({len(candidates)} total)")
        for i, cand in enumerate(candidates):
            lines.append(f"  Candidate {i}: {self.graph_to_text(cand)}")
        lines.append("")

        lines.append(
            "[TASK] Select the candidate index that best matches the true "
            "causal-timescale graph. Respond with:\n"
            "Selected: <index>\nEdges: <edge list>"
        )
        return "\n".join(lines)

    def to_completion(self, gt_graph: dict, gt_index: int) -> str:
        """Build the expected LLM completion for one training example."""
        return (
            f"Selected: {gt_index}\n"
            f"Edges: {self.graph_to_text(gt_graph)}"
        )

    # ------------------------------------------------------------------
    # Text → graph
    # ------------------------------------------------------------------

    def completion_to_graph(self, completion: str, n_nodes: int) -> Optional[dict]:
        """Parse an LLM completion back into a gunfolds graph dict.

        Returns None if parsing fails.
        """
        try:
            edge_line = ""
            for line in completion.strip().splitlines():
                if line.startswith("Edges:"):
                    edge_line = line[len("Edges:"):].strip()
                    break
            if not edge_line or edge_line == "(no edges)":
                return self._empty_graph(n_nodes)
            return self._text_to_graph(edge_line, n_nodes)
        except Exception:
            return None

    def completion_to_index(self, completion: str) -> Optional[int]:
        """Parse the selected candidate index from an LLM completion."""
        for line in completion.strip().splitlines():
            if line.startswith("Selected:"):
                try:
                    return int(line.split(":", 1)[1].strip())
                except ValueError:
                    return None
        return None

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _split_edges(graph: dict) -> tuple[list, list]:
        """Return (directed_edges, bidirected_edges) as sorted lists of (src, tgt)."""
        directed = []
        bidirected = []
        seen_bi = set()

        for src, targets in graph.items():
            for tgt, etype in targets.items():
                if etype in (EDGE_TYPE_DIRECTED, EDGE_TYPE_BOTH):
                    directed.append((src, tgt))
                if etype in (EDGE_TYPE_BIDIRECTED, EDGE_TYPE_BOTH):
                    key = (min(src, tgt), max(src, tgt))
                    if key not in seen_bi:
                        seen_bi.add(key)
                        bidirected.append(key)
        return directed, bidirected

    @staticmethod
    def _empty_graph(n_nodes: int) -> dict:
        return {i + 1: {} for i in range(n_nodes)}

    @staticmethod
    def _text_to_graph(edge_text: str, n_nodes: int) -> dict:
        """Parse 'a->b, c<->d, ...' back into a gunfolds graph dict."""
        graph: dict = {i + 1: {} for i in range(n_nodes)}
        for token in edge_text.split(","):
            token = token.strip()
            if "<->" in token:
                parts = token.split("<->")
                src, tgt = int(parts[0].strip()), int(parts[1].strip())
                # Merge with existing entry
                _set_edge(graph, src, tgt, EDGE_TYPE_BIDIRECTED)
                _set_edge(graph, tgt, src, EDGE_TYPE_BIDIRECTED)
            elif "->" in token:
                parts = token.split("->")
                src, tgt = int(parts[0].strip()), int(parts[1].strip())
                _set_edge(graph, src, tgt, EDGE_TYPE_DIRECTED)
        return graph


def _set_edge(graph: dict, src: int, tgt: int, new_type: int) -> None:
    """Add or upgrade an edge type in-place."""
    existing = graph[src].get(tgt, 0)
    if existing == 0:
        graph[src][tgt] = new_type
    elif existing != new_type:
        graph[src][tgt] = EDGE_TYPE_BOTH
